[
  {
    id: '-KdGz8uOr7A-Kwr1Jddq',
    acceptableCards: [
      {
        name: 'amex',
        company: 'American Express',
        operation: ['Crédito'],
      },
      {
        name: 'diners',
        company: 'Diners Club',
        operation: ['Crédito'],
      },
      {
        name: 'elo',
        company: 'Elo',
        operation: ['Crédito'],
      },
      {
        name: 'hiper',
        company: 'Hipercard',
        operation: ['Crédito'],
      },
      {
        name: 'master',
        company: 'Mastercard',
        operation: ['Crédito', 'Débito'],
      },
      {
        name: 'visa',
        company: 'Visa',
        operation: ['Crédito', 'Débito'],
      },
    ],
    config: {
      productionFactor: {
        saturday: 1,
        sunday: 1,
        monday: 1,
        tuesday: 1,
        wednesday: 1,
        thursday: 1,
        friday: 1,
      },
      deliveryMode: {
        delivery: true,
        driveThru: true,
      },
      takeAway: false,
      monkeyMode: false,
      gateway: 'iugu',
    },
    companyId: '-KdGyq0LACjEHxzTUIVK',
    address: 'Av. Visconde Rio Branco, 5566 - Aerolândia',
    informative: '',
    location: {
      city: 'fortaleza',
      latitude: -3.7700952,
      longitude: -38.516902,
    },
    logoUrl:
      'https://firebasestorage.googleapis.com/v0/b/pglv-dev.appspot.com/o/logos_filiais%2Fcicloburger.png?alt=media&token=23f34266-2fb6-4932-a379-98fb016a5daf',
    fantasyName: 'Ciclo Burguer',
    contact: {
      cellPhone: '0858532277274',
    },
    hasQueue: false,
    isFull: false,
    isActive: true,
    category: 'alimentacao',
    onlinePaymentFee: 0,
    isCurrentClosed: false,
    paused: false,
    isFavouritedByCurrentUser: false,
    deliveryTime: 0,
  },
  {
    id: '-M_MmocDvu-bEFU018f9',
    acceptableCards: [],
    config: {
      productionFactor: {
        saturday: 1,
        sunday: 1,
        monday: 1,
        tuesday: 1,
        wednesday: 1,
        thursday: 1,
        friday: 1,
      },
      fidelity: {
        description: '---',
        name: '---',
      },
      deliveryMode: {
        delivery: true,
        driveThru: true,
      },
      takeAway: true,
      monkeyMode: false,
      gateway: 'iugu',
      storeTax: {
        storeTaxInfo: {
          delivery: 0,
          driveThru: 0,
        },
        pglvTaxInfo: {
          clientPay: 0,
          delivery: 0,
          driveThru: 0,
        },
      },
      productionConstants: {
        DEFAULT_PRODUCTION_TIME: 60,
        INTERVAL_THRESHOLD: 15,
        PICKUP_KG_MULTIPLIER: 10,
        PICKUP_QTY_MULTIPLIER: 2,
        PICKUP_SECTION_MULTIPLIER: 30,
        CHECKOUT_KG_MULTIPLIER: 12,
        CHECKOUT_QTY_MULTIPLIER: 6,
        SETUP_AND_FINISH_TIME: 600,
        SUBSTITUTION_CONST: 180,
        SUBSTITUTION_PERCENTAGE: 0.1,
        SUBSTITUTION_KG_MULTIPLIER: 30,
        SUBSTITUTION_UN_MULTIPLIER: 30,
        SETUP_KG_PRODUCT_MULTIPLIER: 30,
        SETUP_UN_PRODUCT_MULTIPLIER: 20,
      },
      beta: {
        betaUsers: [
          'lucasnoroes@gmail.com',
          'alysson.macedo@gmail.com',
          'caioalbuquerque95@gmail.com',
        ],
      },
    },
    companyId: '-MabajQy2y91jjfib82',
    address: 'Rua Prof. Álvaro Rodrigues, 355 - Botafogo',
    informative: '',
    location: {
      city: 'Rio de Janeiro',
      latitude: -22.952342982844414,
      longitude: -43.18430487528587,
    },
    logoUrl:
      'https://institucional.hortifruti.com.br/wp-content/themes/hortifruti-2019/img/logomarca-hortifruti-footer.png',
    whitelabelLogoUrl: 'https://url-whitelabel-logo',
    fantasyName: 'Hortifruti Botafogo - Fila 9',
    s3Info: {
      bucketName: '',
      region: 'us-east-1',
    },
    contact: {
      cellPhone: '(21) 97153-5217',
      reception: '(21) 2117-9350',
    },
    hasQueue: true,
    isFull: false,
    isActive: true,
    onlinePaymentFee: 0,
    isCurrentClosed: false,
    paused: false,
    isFavouritedByCurrentUser: false,
    deliveryTime: 0,
  },
  {
    id: '-N2IQmW1m62i-2Jmkq6l',
    acceptableCards: [
      {
        name: 'alelo',
        company: 'Alelo Alimentação/Refeição',
        operation: ['Débito'],
      },
      {
        name: 'amex',
        company: 'American Express',
        operation: ['Crédito'],
      },
      {
        name: 'elo',
        company: 'Elo',
        operation: ['Crédito', 'Débito'],
      },
      {
        name: 'fortb',
        company: 'FortBrasil',
        operation: ['Crédito'],
      },
      {
        name: 'greenc',
        company: 'GreenCard Alimentação',
        operation: ['Débito'],
      },
      {
        name: 'hiper',
        company: 'Hipercard',
        operation: ['Crédito', 'Débito'],
      },
      {
        name: 'liber',
        company: 'Libercard',
        operation: ['Crédito', 'Débito'],
      },
      {
        name: 'master',
        company: 'Mastercard',
        operation: ['Crédito', 'Débito'],
      },
      {
        name: 'nutri',
        company: 'Nutricash Alimentação',
        operation: ['Débito'],
      },
      {
        name: 'polic',
        company: 'Policard Alimentação',
        operation: ['Débito'],
      },
      {
        name: 'sodexo',
        company: 'Sodexo',
        operation: ['Débito'],
      },
      {
        name: 'soro',
        company: 'Sorocred',
        operation: ['Crédito'],
      },
      {
        name: 'upbrasil',
        company: 'UP Brasil',
        operation: ['Crédito'],
      },
      {
        name: 'valec',
        company: 'Valecard',
        operation: ['Débito'],
      },
      {
        name: 'vales',
        company: 'ValeShop',
        operation: ['Débito'],
      },
      {
        name: 'visa',
        company: 'Visa',
        operation: ['Crédito', 'Débito'],
      },
      {
        name: 'vr',
        company: 'VR',
        operation: ['Débito'],
      },
    ],
    config: {
      productionFactor: {
        saturday: 1,
        sunday: 1,
        monday: 1,
        tuesday: 1,
        wednesday: 1,
        thursday: 1,
        friday: 1,
      },
      deliveryMode: {
        delivery: true,
        driveThru: false,
      },
      takeAway: false,
      monkeyMode: false,
      gateway: 'juno',
      storeTax: {
        storeTaxInfo: {
          delivery: 10,
          driveThru: 0,
        },
        pglvTaxInfo: {
          clientPay: 0,
          delivery: 0,
          driveThru: 0,
        },
      },
    },
    companyId: '-N2IN4n9J1n38tFqRJqt',
    address: 'Rua Doutor Jurandyr Nunes, nº 441, Lagoa Sapiranga',
    informative: '',
    location: {
      city: 'fortaleza',
      latitude: -3.791758778115023,
      longitude: -38.473329636874574,
    },
    logoUrl:
      'https://firebasestorage.googleapis.com/v0/b/project-482087131936180168.appspot.com/o/logos_filiais%2Flogo-super-barn.png?alt=media&token=8fb4fb8f-5acf-47fa-9965-ce530ae3a6af',
    whitelabelLogoUrl: 'https://url-whitelabel-logo',
    fantasyName: 'Super Barn',
    s3Info: {
      bucketName: '',
      region: 'us-east-1',
    },
    contact: {
      cellPhone: '(85) 99277-6784',
      reception: '(85) 99277-6784',
    },
    hasQueue: true,
    isFull: false,
    isActive: true,
    onlinePaymentFee: 0,
    isCurrentClosed: false,
    paused: false,
    isFavouritedByCurrentUser: false,
    deliveryTime: 0,
  },
];
